sources:
  - name: Ice Den Chandler
    provider: rss
    state: AZ
    city: Chandler
    url: "https://www.icedenchandler.com/event_rss_feed?tags=2703965%2C2703970%2C2704012"

  - name: Ice Den Scottsdale
    provider: rss
    state: AZ
    city: Scottsdale
    url: "https://www.icedenscottsdale.com/event_rss_feed?tags=2670384%2C2670407%2C2678497%2C2662957"

  - name: Mullett Arena
    provider: sportified
    state: AZ
    city: Tempe
    pages:
      - url: "https://mullett.sportified.net/pages/hockey/sticktime"
        event_type: "Stick Time"
      - url: "https://mullett.sportified.net/pages/hockey/adult-open-hockey"
        event_type: "Open Hockey"
      - url: "https://mullett.sportified.net/pages/hockey/flow-hockey"
        event_type: "Flow Hockey"

  - name: AZ Ice Peoria
    provider: daysmart
    company: azice
    facility_id: 1
    state: AZ
    city: Peoria
    days_ahead: 30
    chunk_days: 3
    chunk_workers: 5
    register_fallback: "https://apps.daysmartrecreation.com/dash/x/azice/programs/6/levels"

  - name: AZ Ice Arcadia
    provider: daysmart
    company: azice
    facility_id: 3
    state: AZ
    city: Phoenix
    days_ahead: 30
    chunk_days: 3
    chunk_workers: 5
    register_fallback: "https://apps.daysmartrecreation.com/dash/x/azice/programs/6/levels"
